services:
  pethealth_backend:
    container_name: pethealth-api
    build: .
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "50001:50001"
    volumes:
      - ./public:/app/go/public
      - ./:/app/go
    depends_on:
      pethealth_db:
        condition: service_healthy
    networks:
      - pethealth-nw

  pethealth_db:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: pethealth-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pethealth_db_volumes:/var/lib/postgresql/data
    networks:
      - pethealth-nw
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  pethealth_redis:
    image: redis:8.0.2-alpine
    container_name: pethealth-redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    restart: unless-stopped
    volumes:
      - pethealth_cache:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - pethealth-nw

networks:
  pethealth-nw:
    driver: bridge
volumes:
  pethealth_db_volumes:
  pethealth_cache: