basePath: /api
definitions:
  github_com_231031_wellpaw-backend_internal_model.ActivityLevel:
    enum:
    - 0
    - 1
    - 2
    - 3
    type: integer
    x-enum-varnames:
    - INACTIVE
    - SOMEACTIVE
    - ACTIVE
    - VERYACTIVE
  github_com_231031_wellpaw-backend_internal_model.BcsType:
    enum:
    - 0
    - 1
    - 2
    - 3
    - 4
    type: integer
    x-enum-varnames:
    - VERYTHIN
    - THIN
    - IDEAL
    - OVERWEIGHT
    - OBESITY
  github_com_231031_wellpaw-backend_internal_model.CalendarType:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - VACCINE
    - DRUG
    - APPOINTMENT
  github_com_231031_wellpaw-backend_internal_model.CupFoodPet:
    properties:
      food_pet_food_plan_id:
        type: integer
      id:
        type: integer
      unit_type:
        type: number
    type: object
  github_com_231031_wellpaw-backend_internal_model.DiseaseType:
    enum:
    - 0
    - 1
    - 2
    - 3
    - 4
    type: integer
    x-enum-varnames:
    - RINGWORM
    - SCABIES
    - HEALTHY
    - DEMODICOSIS
    - PYODERMA
  github_com_231031_wellpaw-backend_internal_model.Food:
    properties:
      brand:
        type: string
      energy:
        type: number
      fat:
        type: number
      food_pet_food_plans:
        items:
          $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.FoodPetFoodPlan'
        type: array
      id:
        type: integer
      image_path:
        type: string
      moist:
        type: number
      name:
        type: string
      protein:
        type: number
      quantity:
        type: integer
      type:
        $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.FoodType'
      user:
        allOf:
        - $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.User'
        description: Relationships
      user_id:
        type: integer
      weight:
        type: number
    type: object
  github_com_231031_wellpaw-backend_internal_model.FoodPetFoodPlan:
    properties:
      cup_food_pet:
        items:
          $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.CupFoodPet'
        type: array
      food:
        allOf:
        - $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.Food'
        description: |-
          Relationships
          PetFoodPlan       *PetFoodPlan       `gorm:"foreignKey:PetFoodPlanID" json:"pet_food_plan,omitempty"`
      food_id:
        type: integer
      id:
        type: integer
      pet_food_plan_detail:
        items:
          $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.PetFoodPlanDetail'
        type: array
      pet_food_plan_id:
        type: integer
    type: object
  github_com_231031_wellpaw-backend_internal_model.FoodType:
    enum:
    - 0
    - 1
    - 2
    - 3
    type: integer
    x-enum-varnames:
    - DRY
    - WET
    - TREATS
    - SUPPLEMENTS
  github_com_231031_wellpaw-backend_internal_model.FrequentlyType:
    enum:
    - 0
    - 1
    - 2
    - 3
    - 4
    type: integer
    x-enum-varnames:
    - NOT
    - DAY
    - WEEK
    - MONTH
    - YEAR
  github_com_231031_wellpaw-backend_internal_model.HTTPResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
  github_com_231031_wellpaw-backend_internal_model.Payment:
    properties:
      created_at:
        type: string
      currency:
        type: string
      id:
        type: integer
      price:
        type: integer
      status:
        $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.PaymentStatusType'
      stripe_payment_id:
        type: string
      subscription_period_end:
        type: string
      updated_at:
        type: string
      user:
        allOf:
        - $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.User'
        description: Relationships
      user_id:
        type: integer
    type: object
  github_com_231031_wellpaw-backend_internal_model.PaymentStatusType:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - PENDING
    - SUCCEEDED
    - FAILED
  github_com_231031_wellpaw-backend_internal_model.Pet:
    properties:
      activity_events:
        items:
          $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.PetActivityCalendar'
        type: array
      birth_date:
        type: string
      breed:
        type: string
      created_at:
        type: string
      id:
        type: integer
      image_path:
        type: string
      name:
        type: string
      pet_details:
        description: |-
          Relationships
          User           *User                 `gorm:"foreignKey:UserID" json:"user,omitempty"`
        items:
          $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.PetDetail'
        type: array
      pet_food_plans:
        items:
          $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.PetFoodPlan'
        type: array
      pet_skin_images:
        items:
          $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.PetSkinImage'
        type: array
      sex_type:
        $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.SexType'
      type:
        $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.PetType'
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  github_com_231031_wellpaw-backend_internal_model.PetActivityCalendar:
    properties:
      id:
        type: integer
      pet:
        allOf:
        - $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.Pet'
        description: Relationships
      pet_calendar:
        $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.PetCalendar'
      pet_calendar_id:
        type: integer
      pet_id:
        type: integer
    type: object
  github_com_231031_wellpaw-backend_internal_model.PetCalendar:
    properties:
      activity_events:
        description: Relationships
        items:
          $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.PetActivityCalendar'
        type: array
      created_at:
        type: string
      end_date:
        type: string
      frequently:
        $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.FrequentlyType'
      id:
        type: integer
      name:
        type: string
      notation:
        type: string
      start_datetime:
        type: string
      type:
        $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.CalendarType'
    type: object
  github_com_231031_wellpaw-backend_internal_model.PetDetail:
    properties:
      activity_level:
        $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.ActivityLevel'
      bcs:
        allOf:
        - $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.BcsType'
        description: Body Condition Score
      created_at:
        type: string
      energy:
        type: number
      fat:
        type: number
      gestation:
        type: boolean
      gestation_startdate:
        type: string
      id:
        type: integer
      is_adult:
        type: boolean
      lactation:
        type: boolean
      neutered:
        type: boolean
      pet_food_plan_details:
        description: |-
          Relationships
          Pet                *Pet                 `gorm:"foreignKey:PetID" json:"pet,omitempty"`
        items:
          $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.PetFoodPlanDetail'
        type: array
      pet_food_plan_history:
        items:
          $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.PetFoodPlanHistory'
        type: array
      pet_id:
        type: integer
      protein:
        description: Fixed typo from 'protien'
        type: number
      weight:
        type: number
    type: object
  github_com_231031_wellpaw-backend_internal_model.PetFoodPlan:
    properties:
      active:
        type: boolean
      created_at:
        type: string
      food_pet_food_plans:
        description: |-
          Relationships
          Pet                *Pet                 `gorm:"foreignKey:PetID" json:"pet,omitempty"`
        items:
          $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.FoodPetFoodPlan'
        type: array
      id:
        type: integer
      name:
        type: string
      pet_food_plan_history:
        items:
          $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.PetFoodPlanHistory'
        type: array
      pet_id:
        type: integer
      unit:
        $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.UnitType'
    type: object
  github_com_231031_wellpaw-backend_internal_model.PetFoodPlanDetail:
    properties:
      amount:
        type: number
      energy_intake:
        type: number
      fat_intake:
        type: number
      food_pet_food_plan:
        allOf:
        - $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.FoodPetFoodPlan'
        description: Relationships
      food_pet_food_plan_id:
        type: integer
      id:
        type: integer
      pet_detail_id:
        type: integer
      protein_intake:
        type: number
    type: object
  github_com_231031_wellpaw-backend_internal_model.PetFoodPlanHistory:
    properties:
      created_at:
        type: string
      id:
        type: integer
      pet_detail_id:
        type: integer
      pet_food_plan_id:
        type: integer
    type: object
  github_com_231031_wellpaw-backend_internal_model.PetSkinImage:
    properties:
      confident:
        type: integer
      created_at:
        type: string
      id:
        type: integer
      image_evidence:
        type: string
      image_path:
        type: string
      labeled:
        $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.DiseaseType'
      pet_id:
        type: integer
      predicted:
        $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.DiseaseType'
      updated_at:
        type: string
    type: object
  github_com_231031_wellpaw-backend_internal_model.PetType:
    enum:
    - 0
    - 1
    type: integer
    x-enum-varnames:
    - DOG
    - CAT
  github_com_231031_wellpaw-backend_internal_model.SexType:
    enum:
    - 0
    - 1
    type: integer
    x-enum-varnames:
    - FEMALE
    - MALE
  github_com_231031_wellpaw-backend_internal_model.TierType:
    enum:
    - 0
    - 1
    - 2
    - 3
    type: integer
    x-enum-varnames:
    - FREE
    - WEEKS
    - MONTHS
    - YEARS
  github_com_231031_wellpaw-backend_internal_model.UnitType:
    enum:
    - 0
    - 1
    type: integer
    x-enum-varnames:
    - GRAM
    - CUP
  github_com_231031_wellpaw-backend_internal_model.User:
    properties:
      bcs_free:
        type: integer
      created_at:
        type: string
      device_token:
        type: string
      disease_free:
        type: integer
      email:
        type: string
      first_name:
        type: string
      food_free:
        type: integer
      food_plan_free:
        type: integer
      foods:
        items:
          $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.Food'
        type: array
      id:
        type: integer
      last_name:
        type: string
      noti_calendars:
        type: boolean
      noti_food:
        type: boolean
      password:
        type: string
      payment_plan:
        $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.TierType'
      payments:
        items:
          $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.Payment'
        type: array
      pets:
        description: Relationships
        items:
          $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.Pet'
        type: array
      profile_free:
        type: integer
      updated_at:
        type: string
    type: object
host: localhost:50001
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: WellPaw API is a RESTful API for managing and tracking pet health
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: WellPaw API
  version: "1.0"
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: register a new user
      parameters:
      - description: Register payload
        in: body
        name: RegisterPayload
        required: true
        schema:
          $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.HTTPResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_231031_wellpaw-backend_internal_model.HTTPResponse'
      summary: Register User
      tags:
      - Authentication
schemes:
- http
swagger: "2.0"
